# Generated by Django 5.1.3 on 2026-02-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_travelers',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
